// Generated by Xata Codegen 0.27.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "settings",
    columns: [
      { name: "userId", type: "string", unique: true },
      { name: "view", type: "string", notNull: true, defaultValue: "month" },
    ],
  },
  {
    name: "events",
    columns: [
      { name: "title", type: "string" },
      { name: "description", type: "text" },
      { name: "userId", type: "string", unique: true },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Settings = InferredTypes["settings"];
export type SettingsRecord = Settings & XataRecord;

export type Events = InferredTypes["events"];
export type EventsRecord = Events & XataRecord;

export type DatabaseSchema = {
  settings: SettingsRecord;
  events: EventsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Davidson-Conrad-s-workspace-rongcb.us-east-1.xata.sh/db/calendar",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
